language: csharp
dist: trusty
sudo: required
dotnet: 2.0.0

branches:
  only:
    - master
    - develop

solution: TrainersMap.sln
install:
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
  - nuget restore TrainersMap.sln
  - dotnet restore

script:
  - msbuild /p:Configuration=Release TrainersMap.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./TrainersMap.Api.Tests.Xunit/bin/Release/TrainersMap.Api.Tests.Xunit.dll