language: csharp
solution: TrainersMap.sln
install:
  - nuget install xunit.runner.console -Version 2.3.1 -OutputDirectory testrunner
  - nuget restore TrainersMap.sln
script:
  - msbuild /p:Configuration=Release TrainersMap.sln
  - mono ./testrunner/xunit.runner.console.2.3.1/tools/xunit.console.exe ./TrainersMap.Api.Tests/bin/Release/TrainersMap.Api.Tests.dll