language: csharp
dist: trusty
sudo: required
dotnet: 2.0.0

branches:
  only:
    - master
    - develop

solution: TrainersMap.sln
install:
  - nuget restore TrainersMap.sln
  - dotnet restore

script:
  - msbuild /p:Configuration=Release TrainersMap.sln
  - dotnet test ./TrainersMap.Api.Tests.Xunit