language: csharp
solution: TrainersMap.sln
install:
  - nuget restore TrainersMap.sln
script:
  - msbuild /p:Configuration=Release TrainersMap.sln
  - mono ./packages/xunit.runners.*/tools/xunit.console.clr4.exe ./TrainersMap.Api.Tests/bin/Release/TrainersMap.Api.Tests.dll