language: csharp
solution: TrainersMap.sln
install:
  - nuget install xunit.runners -Version 2.0.0 -OutputDirectory testrunner
  - nuget restore TrainersMap.sln
script:
  - msbuild /p:Configuration=Release TrainersMap.sln
  - mono ./testrunner/xunit.runners.*/tools/xunit.console.clr4.exe ./TrainersMap.Api.Tests/bin/Release/TrainersMap.Api.Tests.dll