language: csharp
solution: TrainersMap.sln
install:
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
  - nuget restore TrainersMap.sln
script:
  - xbuild /p:Configuration=Release TrainersMap.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./TrainersMap.Api.Tests/bin/Release/TrainersMap.Api.Tests.dll